### ISSUE TITLE
이번주 TODO List

### ISSUE THREAD

**Issue by bread-kwon** [bread-kwon/pro-bff#8]
## Overview

BFF Server 구현을 위해 이번주에 확인할 사항 (8/2 - 8/6)

## How

- [ ] API 모듈 정리
- [ ] dev 배포
- [ ] tsconfig-paths 적용
- [ ] data source 연동
  - [ ] 상담(remodelingStepts)
  - [ ] 공지사항(notice)
  - [ ] partner
  - [ ] 계약서
  - [ ] 포트폴리오
  - [ ] 사진
- [ ] services 진행

## Check

- [ ] 인증서
- [ ] domain
- [ ] 로그인 및 cookie
- [ ] key-value store 유무
- [ ] lint-staged

**Comment by bread-kwon** [comment]
## Memo

- schema
- client
- page
- graphql
- 알림
- monitoring
